name: wastagram
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^0.5.0
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  intl: ^0.16.1
  image_picker: ^0.6.7+11
  location: ^3.0.2
  share: ^0.6.5+2
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true