name: wastagram
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.4
  firebase_storage: ^3.1.3
  intl: ^0.16.1
  image_picker: ^0.6.3
  location: ^2.5.4
  share: ^0.6.3
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true